@startwbs
<style>
wbsDiagram {
  FontName Lato
  FontColor #383939
  LineColor #8A8B8B
  node { BackgroundColor #FFFFFF; LineColor #8A8B8B; RoundCorner 8; Padding 6; Margin 4 }
  :depth(0) { BackgroundColor #54A2CC; FontColor #FFFFFF; FontStyle bold; LineColor #54A2CC }
  :depth(1) { BackgroundColor #EAF3FA; LineColor #54A2CC; FontStyle bold }
  :depth(2) { BackgroundColor #FCF3E0; LineColor #EEB348 }
}
</style>
* Contextual\n<size:11>weight 0.1</size>
** EPLEX Score\n<size:10>weight 1</size>
*** EPLEX score
**< Workplace Discrimination\n<size:10>weight 0.33</size>
***< WBL Workplace Index
** Regulatory Frameworks\n<size:10>weight 0.33</size>
*** WBL Pay & Parenthood Index
**< Financial Inclusion\n<size:10>weight 0.33</size>
***< WBL Entrepreneurship Index
@endwbs
